<?php
/**
 * Tables in synergy
 */
define("TBL_ENTITIES","entities");
define("TBL_DISTRICTS","districts");
define("TBL_ETYPES","etypes");
define("TBL_SECTORS","sectors");
define("TBL_SKILLING","skilling");
define("TBL_SKILLAREA","skillingareas");
define("TBL_SKILLVALUES","skillvalues");
define("TBL_LOG","translog");
define("TBL_USERPERM","userperm");
define("TBL_USERS","users");
define("TBL_SIZES","entitysize");
define("TBL_CRITERIA","idcat");
define("TBL_CRITERIAREASON","idcriteria");
define("TBL_TRANS","translog");
define("TBL_PAYMENTS","payments");
define("TBL_RETURNS","monthlyreturns");
define("TBL_REGIONS","myregion");
